# Problem 4 part 2

# Huy Le

In [6]:
import numpy as np

M1 = np.array([[ 2,  1,  0],
               [-1,  1,  2],
               [ 0,  3,  1]], dtype=float)

M2 = np.array([[1, 2, 3],
               [0, 1, 4],
               [5, 6, 0]], dtype=float)

M3 = np.array([[-2,  1,  1],
               [ 3,  1,  0],
               [ 4,  2,  1]], dtype=float)

mats = [M1, M2, M3]

np.set_printoptions(precision=6, suppress=True)

for i, Matrix in enumerate(mats, start=1):
    Matrix_inv = np.linalg.inv(Matrix)
    prod = Matrix @ Matrix_inv
    det = np.linalg.det(Matrix)

    print(f"\nM{i} =\n{Matrix}")

    print(f"det(M{i}) = {det}")

    print(f"M{i}^-1 =\n{Matrix_inv}")

    print(f"M{i} * M{i}^-1 =\n{prod}")
    
    print("Close to identity?", np.allclose(prod, np.eye(3)))



M1 =
[[ 2.  1.  0.]
 [-1.  1.  2.]
 [ 0.  3.  1.]]
det(M1) = -8.999999999999998
M1^-1 =
[[ 0.555556  0.111111 -0.222222]
 [-0.111111 -0.222222  0.444444]
 [ 0.333333  0.666667 -0.333333]]
M1 * M1^-1 =
[[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]
Close to identity? True

M2 =
[[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]
det(M2) = 0.9999999999999987
M2^-1 =
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
M2 * M2^-1 =
[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
Close to identity? True

M3 =
[[-2.  1.  1.]
 [ 3.  1.  0.]
 [ 4.  2.  1.]]
det(M3) = -2.9999999999999996
M3^-1 =
[[-0.333333 -0.333333  0.333333]
 [ 1.        2.       -1.      ]
 [-0.666667 -2.666667  1.666667]]
M3 * M3^-1 =
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]
Close to identity? True


# Problem 5

In [17]:
import pandas as pd
import numpy as np

# Load csv file
df = pd.read_csv('housing/kc_house_data.csv')

# Remove id, date, and zipcode columns
features_to_analyze = df.drop(['id', 'date', 'zipcode', 'price'], axis=1).columns.tolist()


print("\nQUESTION 1: Average, min, max, variance for each feature:")


# Stats table
stats_dict = {
    'Feature': [],
    'Average': [],
    'Min': [],
    'Max': [],
    'Variance': []
}

for feature in features_to_analyze:
    stats_dict['Feature'].append(feature)
    stats_dict['Average'].append(df[feature].mean())
    stats_dict['Min'].append(df[feature].min())
    stats_dict['Max'].append(df[feature].max())
    stats_dict['Variance'].append(df[feature].var())

stats_df = pd.DataFrame(stats_dict)

print("\n Stats of all features:")
print(stats_df.to_string(index=False))

# Find features with lowest and highest average
min_avg_idx = stats_df['Average'].idxmin()
max_avg_idx = stats_df['Average'].idxmax()


print("\n Features with lowest and highest average:")

print(f"\nLowest Average:")
print(f"  Feature: {stats_df.loc[min_avg_idx, 'Feature']}")
print(f"  Average: {stats_df.loc[min_avg_idx, 'Average']:.6f}")

print(f"\nHighest Average:")
print(f"  Feature: {stats_df.loc[max_avg_idx, 'Feature']}")
print(f"  Average: {stats_df.loc[max_avg_idx, 'Average']:.6f}")

# Find features with lowest and highest variance
min_var_idx = stats_df['Variance'].idxmin()
max_var_idx = stats_df['Variance'].idxmax()


print("Features with lowest and highest variance:")

print(f"\nLowest Variance:")
print(f"  Feature: {stats_df.loc[min_var_idx, 'Feature']}")
print(f"  Variance: {stats_df.loc[min_var_idx, 'Variance']:.6f}")

print(f"\nHighest Variance:")
print(f"  Feature: {stats_df.loc[max_var_idx, 'Feature']}")
print(f"  Variance: {stats_df.loc[max_var_idx, 'Variance']:.6f}")


print("\nQUESTION 2: Correlation coefficient of each feature with the response: ")

# Compute correlation with price
correlations = []
for feature in features_to_analyze:
    corr = df[feature].corr(df['price'])
    correlations.append({'Feature': feature, 'Correlation with Price': corr})

corr_df = pd.DataFrame(correlations)
corr_df = corr_df.sort_values('Correlation with Price', ascending=False)

print("\nCorrelation coefficient of each feature with price:")
print(corr_df.to_string(index=False))

# Find positively correlated features
positive_corr = corr_df[corr_df['Correlation with Price'] > 0]
print("\n Positively correlated features:")
print(positive_corr.to_string(index=False))

# Find the highest positive correlation
max_corr_feature = corr_df.iloc[0]
print("\n Feature with highest positive correlation:")
print(f"  Feature: {max_corr_feature['Feature']}")
print(f"  Correlation: {max_corr_feature['Correlation with Price']:.6f}")


print("\n QUESTION 3: Features with negative correlation?")

# Find negatively correlated features
neg_corr = corr_df[corr_df['Correlation with Price'] < 0]

if len(neg_corr) > 0:
    print("\nFeatures with negative correlation coefficient with price:")
    print(neg_corr.to_string(index=False))
else:
    print("\nNo features with negative correlation coefficient with price.")


QUESTION 1: Average, min, max, variance for each feature:

 Stats of all features:
      Feature      Average       Min          Max     Variance
     bedrooms     3.370842    0.0000      33.0000 8.650150e-01
    bathrooms     2.114757    0.0000       8.0000 5.931513e-01
  sqft_living  2079.899736  290.0000   13540.0000 8.435337e+05
     sqft_lot 15106.967566  520.0000 1651359.0000 1.715659e+09
       floors     1.494309    1.0000       3.5000 2.915880e-01
   waterfront     0.007542    0.0000       1.0000 7.485226e-03
         view     0.234303    0.0000       4.0000 5.872426e-01
    condition     3.409430    1.0000       5.0000 4.234665e-01
        grade     7.656873    1.0000      13.0000 1.381703e+00
   sqft_above  1788.390691  290.0000    9410.0000 6.857347e+05
sqft_basement   291.509045    0.0000    4820.0000 1.958727e+05
     yr_built  1971.005136 1900.0000    2015.0000 8.627973e+02
 yr_renovated    84.402258    0.0000    2015.0000 1.613462e+05
          lat    47.560053   47.15